### ISSUE TITLE
Ember-forms doesnt update binding, keeps using the old record

### ISSUE THREAD

**Issue by BenjaminHorn** [indexiatech/ember-forms#23]
I have a form bound to a book record. After i saved i want to "null out" the rcord, so i create a new one , but ember-forms keeps using the old one. Is it he normal behaviour? Or there is a better way to do it?

Here is a JsBin: http://jsbin.com/pexolude/48/edit and the stackoveflow link with solution:
http://stackoverflow.com/questions/24194731/emberjs-save-record-mockjax/

**Comment by xcskier56** [comment]
This perfectly solved my issues when replacing the model. What is the status on this? A pull request would be great.

**Comment by chbonser** [comment]
This also solves my issue.  I'm also interested to know the status of a PR. Any news?

**Comment by asaf** [comment]
PR #92 merged.
