### ISSUE TITLE
Does it work w/out ember-data?

### ISSUE THREAD

**Issue by toranb** [indexiatech/ember-forms#31]
Thanks for an amazingly helpful/well documented project! keep up the great work!

2 questions

1.) if I only have a basic ember object (no ember-data) will this work?
2.) how do I inject a simple "model" and use the markup for this very simple app?

https://github.com/toranb/ember-form-example

the controller is here

https://github.com/toranb/ember-form-example/blob/master/js/app/controllers/people.js

the hbs is here

https://github.com/toranb/ember-form-example/blob/master/js/templates/people.handlebars

I believe the refactor will remove almost all of this code (I'd like to see the diff but I found the markup I'm using /below isn't working for that model. Do I need a route to "new up" this model? if not how will this library know what model goes w/ my controller?)

```
{{#em-form model=model}}
    {{em-input property="name" label="Full Name" placeholder="Enter a name..."}}
    {{em-input property="password" label="Password" placeholder="And password..." type="password"}}
{{/em-form}}
```

**Comment by rizkytahara** [comment]
@toranb i also have the same problem with bounding the form and the model for the validation to get work... may i know how to solve it?

**Comment by toranb** [comment]
I put together an example app a while back but I'm not sure how recent it is :)

https://github.com/toranb/ember-form-example/commits/master

Later I ended up writing my own validation library for this form validation logic (the only diff is you write the form input /html yourself)

https://github.com/toranb/ember-cli-simple-validation
