### ISSUE TITLE
"undefined is not a function error" in ember-cli Production environment

### ISSUE THREAD

**Issue by camdub** [indexiatech/ember-forms#44]
Ember-forms is working great, but when I run the ember-cli server in production mode I get an `Uncaught TypeError: undefined is not a function` error. Since this only happens in production, I'm not even sure how to start trying to find the source of this. If I remove ember-forms from my app, it works as normal (except the pages using the forms of course).

I suppose I could turn off minification in the production script to try and find the issue.

I am simply including the globals version in my `Brocfile`: `app.import('vendor/ember-forms/dist/globals/main.js');`

Here is a screenshot of the error message which might help: http://inft.ly/fvPryUr

**Comment by yangbai1991** [comment]
Running into this as well

**Comment by asaf** [comment]
@yangbai1991 Sorry I have no time to maintain this project any longer, seeking for maintainers though
