### ISSUE TITLE
Make an ember-cli addon

### ISSUE THREAD

**Issue by samselikoff** [indexiatech/ember-forms#54]
We should make an ember-cli addon for easy install/upgrades

**Comment by hwwan80** [comment]
How can I use it without using ember-cli? Just find that my gulp-based build break after update from 0.4 to 0.5

**Comment by asaf** [comment]
Hey, 

Never tried but once you build the addon manually it generates a js under the dist folder,

Can you try to include the built js into your app?

Let me know if it works

Thanks
