### ISSUE TITLE
Cannot be used without ember-cli after version 0.5.0

### ISSUE THREAD

**Issue by hwwan80** [indexiatech/ember-forms#80]
ember-forms cannot be used without  ember-cli after commit dac53b12bbef1211379fc07c2af3b1095a837b99

**Comment by koryteg** [comment]
true, do you plan on adding back a way to build the dist/globals folder again?

**Comment by timini** [comment]
anyone know how to fix this?

**Comment by spruce** [comment]
Can you use it again?

**Comment by asaf** [comment]
If anyone has still any issues will reopen.

thanks.
