### ISSUE TITLE
Close button icons hard coded

### ISSUE THREAD

**Issue by jackmatt2** [indexiatech/ember-forms#84]
em-modal-confirm.hbs

```javascript
<i class="fa fa-thumbs-o-down"></i>
```

Should this not be 

```javascript
<i {{bind-attr class="cancel-button-icons"}}></i>
```

so the user can override as you can with submit-button-default-icons

**Comment by asaf** [comment]
Hey,

How modal confirm is related to this project?

**Comment by jackmatt2** [comment]
oh yeah.

**Comment by asaf** [comment]
@jackmatt2 ye I think you are confusing with the https://github.com/indexiatech/ember-idx-modal component :)
