### ISSUE TITLE
ember cli 0.2.0-beta.1 install

### ISSUE THREAD

**Issue by koryteg** [indexiatech/ember-forms#88]
the install seems to break when using ember-cli 0.2.0-beta.1. should utilize the `setupPreprocessorRegistry` hook as documented in the docs. https://github.com/ember-cli/ember-cli/releases 

since 0.2.0 is still beta is there a work around to getting this install?

**Comment by spruce** [comment]
Does this still break for you? Because I installed ember-idx-forms right now and it works for me

**Comment by koryteg** [comment]
it is working for me now.

**Comment by asaf** [comment]
Closing as it seems to be working.
