### ISSUE TITLE
Adding me as maintainer

### ISSUE THREAD

**Issue by spruce** [indexiatech/ember-forms#93]
Hey,
Can you add me as a maintainer so that I can edit some pull requests and things like that?

Would be appreciated. Didn't find another way to contact you.

**Comment by vasilakisfil** [comment]
+1.. if you can't maintain the project just step down, don't be selfish :)

**Comment by Kuzirashi** [comment]
Also :+1: this project has to move forward to at least be compatible with latest stable versions.

**Comment by BenjaminHorn** [comment]
+1
@spruce  @vasilakisfil  @Kuzirashi  
It looks like @asaf disappears often for weeks, so  I would suggest to make a new repo.

**Comment by spruce** [comment]
@BenjaminHorn Did already think about that. But I think it's always the last option to consider. I will wait one more week (so it will be a 3 weeks old issue) then I'm gonna create a new repo and also npm stuff and so on

**Comment by leejt489** [comment]
Yeah, I'm starting to get a little frustrated with this.

**Comment by Kuzirashi** [comment]
Soon it should move to new computed property syntax, new attribute binding etc. as Ember 1.12 will be released but seems project is dead.

**Comment by spruce** [comment]
Will do this as first thing on the new repo. Anyone has some good alternative names for the new project?

**Comment by leejt489** [comment]
Maybe ember-quick-forms, kind of like the ember-easy-form project?

**Comment by Kuzirashi** [comment]
`ember-quick-forms` sounds good, but I `ember-rapid-forms` sounds even better :D

**Comment by spruce** [comment]
I like ember-rapid-forms, too.

**Comment by leejt489** [comment]
ember-rapid-forms sounds good.  Can anyone lay out the key differences
between this and the ember-easy-form project, other than that one isn't
available on npm or bower?  That one has a significant following as well.

**Comment by vasilakisfil** [comment]
ember-rapid-forms sounds good! I think name little matters, as long as it is maintained :)

**Comment by asaf** [comment]
Folks. I was in a holiday for 1 month.

Im not leaving a way. We use this project in production in many environments!

If u feel so, u are free to fork, thats the beauty of open source,

The 2nd option is to add maintainers. If there are good candidates ill be more than happy to get some help!

Asaf.

**Comment by spruce** [comment]
Am I a good candidate? :P Would be nice to have someone else also to work on it. 
It would also be nice if you can grant me the right to push to npm so I also can update releases

**Comment by spruce** [comment]
@asaf Can You show any reaction?

**Comment by asaf** [comment]
Please start sending PR first.
Id like to review your code first.
 Thanks!

**Comment by spruce** [comment]
Since I think the response time is way to slow I finally forked this repo and made some first changes. The repo lives here: https://github.com/piceatech/ember-rapid-forms with docs here http://piceatech.github.io/ember-rapid-forms/

To not get an unmainted fork of ember-forms I would ask you to request push access to my project. I will add you when you request it.
@vasilakisfil @leejt489 @Kuzirashi @BenjaminHorn @asaf

**Comment by asaf** [comment]
@spruce Feel free to contact me if you feel like I can do anything.
